spring.application.name=Banking-Application

spring.datasource.url=jdbc:postgresql://dpg-d80c9k3eo5us73fdl0ag-a.oregon-postgres.render.com:5432/banking_db_71ms
spring.datasource.username=banking_db_71ms_user
spring.datasource.password=A7tV32J2altBXjLsE45Fs2j3qmwC58z3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

server.port=${PORT:8080}